[package]
name = "lux_cui"
version = "0.1.0"
edition = "2021"

[dependencies]
inquire = "0.7.5"
serde = "1.0.204"
serde_json = "1.0.120"
tokio = { version = "1.38.1", features = ["rt", "rt-multi-thread", "macros"] }
serde_derive = "1.0.204"
